name: Build JobTitles

on:
  push:
    branches: "main"

concurrency:
  group: build_jt
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x.x

      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: JobTitles
          path: .\bin\Release\JobTitles\*
          if-no-files-found: error
          retention-days: 1
